/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "home": [],
    "about": [],
    "contact": [],
    "student.index": [],
    "student.create": [],
    "student.store": [],
    "student.show": [
        {
            "name": "student",
            "required": true,
            "binding": "id"
        }
    ],
    "student.edit": [
        {
            "name": "student",
            "required": true,
            "binding": "id"
        }
    ],
    "student.update": [
        {
            "name": "student",
            "required": true,
            "binding": "id"
        }
    ],
    "student.destroy": [
        {
            "name": "student",
            "required": true,
            "binding": "id"
        }
    ],
    "grade.index": [],
    "grade.create": [],
    "grade.store": [],
    "grade.show": [
        {
            "name": "grade",
            "required": true,
            "binding": "id"
        }
    ],
    "grade.edit": [
        {
            "name": "grade",
            "required": true,
            "binding": "id"
        }
    ],
    "grade.update": [
        {
            "name": "grade",
            "required": true,
            "binding": "id"
        }
    ],
    "grade.destroy": [
        {
            "name": "grade",
            "required": true,
            "binding": "id"
        }
    ],
    "grade.showStudent": [
        {
            "name": "student",
            "required": true,
            "binding": "id"
        }
    ],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.update": [],
    "logout": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "setting.profile": [],
    "setting.name": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "setting.email": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "setting.password": [],
    "setting.theme": [],
    "setting.avatar": [],
    "subject.index": [],
    "subject.store": [],
    "subject.update": [
        {
            "name": "subject",
            "required": true,
            "binding": "id"
        }
    ],
    "subject.destroy": [
        {
            "name": "subject",
            "required": true,
            "binding": "id"
        }
    ],
    "year.pdf": [
        {
            "name": "grade",
            "required": true,
            "binding": "id"
        }
    ],
    "marks.pdf": [
        {
            "name": "grade",
            "required": true,
            "binding": "id"
        },
        {
            "name": "term",
            "required": true
        }
    ],
    "mark.store": [
        {
            "name": "student",
            "required": true,
            "binding": "id"
        }
    ],
    "mark.show": [
        {
            "name": "student",
            "required": true,
            "binding": "id"
        },
        {
            "name": "term",
            "required": true
        }
    ],
    "mark.update": [
        {
            "name": "mark",
            "required": true
        }
    ],
    "mark.pdf": [
        {
            "name": "student",
            "required": true,
            "binding": "id"
        },
        {
            "name": "term",
            "required": true
        }
    ],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
